# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
